language: go

go:
  - tip
  - "1.15"
  - "1.14"

go_import_path: github.com/delicb/gwc

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
